---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: nginx
  name: nginx
  namespace: nginx-ingress

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: nginx
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: nginx
  namespace: nginx-ingress

