apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30080
      name: http
    - port: 30443
      nodePort: 
      name: https
    - port: 18080
      name: http-mgmt
  selector:
    app: nginx-ingress-lb
