apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - host: {{ ingress_hostname }}
    http:
      paths:
      - backend:
          serviceName: nginx-ingress
          servicePort: 18080
