---

- name: Creates /etc/kubernetes/kubeadm directory
  file: path=/etc/kubernetes/kubeadm/storage  recurse=yes state=directory
  when: >
    inventory_hostname == "kube-master-0"

- name: Copy kube config files
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'step.1.common.yaml.j2', dest: '/etc/kubernetes/kubeadm/storage/step.1.common.yaml'  }  
     - { src: 'step.2.operator.yaml.j2', dest: '/etc/kubernetes/kubeadm/storage/step.2.operator.yaml'  }  
     - { src: 'step.3.cluster.yaml.j2', dest: '/etc/kubernetes/kubeadm/storage/step.3.cluster.yaml'  }  
     - { src: 'step.4.object.yaml.j2', dest: '/etc/kubernetes/kubeadm/storage/step.4.object.yaml'  }  
     - { src: 'step.5.toolbox.yaml.j2', dest: '/etc/kubernetes/kubeadm/storage/step.5.toolbox.yaml'  }  
     - { src: 'step.5.toolbox.yaml.j2', dest: '/etc/kubernetes/kubeadm/storage/step.5.toolbox.yaml'  }  
     - { src: 'taint.sh.j2', dest: '/etc/kubernetes/kubeadm/storage/taint.sh'  }  
  when: >
    inventory_hostname == "kube-master-0"
  register: result

- name:  label and storage ingress box
  shell: sh /etc/kubernetes/kubeadm/storage/taint.sh;
  when: >
    inventory_hostname == "kube-master-0" 
  ignore_errors: yes


