---

- name: install yum-utils device-mapper-persistent-data lvm2
  yum:
     name: "{{ item }}"
     state: present
     update_cache: yes
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add repository
  yum_repository:
    name: docker-ce
    baseurl: https://download.docker.com/linux/centos/docker-ce.repo

- name: install yum-utils device-mapper-persistent-data lvm2
  yum:
     name: "{{ item }}"
     state: present
     update_cache: yes
  loop:
    - containerd.io-1.2.10
    - docker-ce-19.03.4
    - docker-ce-cli-19.03.4

- name: Copy docker deamon iles
  template: src=docker-daemon-centos.json.j2  dest=/etc/docker/daemon.json
  notify: restart docker      

- name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

- name: Install kubelet kubeadm kubectl
  yum:
     name: "{{ item }}"
     state: present
     update_cache: yes
  loop:
    - kubelet
    - kubeadm
    - kubectl
